spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentDB?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate.temp.use_jdbc_metadata_defaults : false

logging:
  level:
    root: INFO